using Shopp_App_.NetCore.Context;
using System.Windows;
using Shopp_App_.NetCore.Model;
using System.Linq;
using System.Windows.Controls;
using System;

namespace Shopp_App_.NetCore
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            using var db = new DataContext();
            gridload.ItemsSource = db.Stores.ToList();
            gridload.AutoGeneratedColumns += Gridload_AutoGeneratedStore;

        }

        private void Gridload_AutoGeneratedStore(object sender, System.EventArgs e)
        {
            try
            {
                DataGrid dataGrid = sender as DataGrid;
                dataGrid.Columns[1].Header = "Անուն";
                dataGrid.Columns[2].Header = "Քանակ";
                dataGrid.Columns[3].Header = "Գին";
                dataGrid.Columns[4].Header = "Ամսաթիվ";
            }
            catch (Exception) { }
        }

        private void Add_Click(object sender, RoutedEventArgs e)
        {

        }
    }
}
